<?php namespace VS\CmsBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository
{
    public function countTotal() 
    {
        $query = $this->getEntityManager()->createQuery('SELECT COUNT(p) FROM VSCmsBundle:Page p');

        return $query->getSingleScalarResult();
    }
    
    public function find($id, $lockMode = null, $lockVersion = null) 
    {
        if(!is_numeric($id)) {
            return $this->findOneBy(array('slug'=>$id));
        }
        
        return parent::find($id, $lockMode, $lockVersion);
    }
    
}
