services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.fixture.general_settings:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\GeneralSettingsFixture
        arguments:
            # - '@sylius.manager.product'
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.general_settings'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.multisite_settings:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\MultiSiteSettingsFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.general_settings'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.taxonomy:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\TaxonomyFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.taxonomy'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.page_categories:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\PageCategoriesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.page_categories'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.application_site:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\ApplicationSiteFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.application_site'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.pages:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\PagesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.pages'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.locales:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\LocalesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.locales'
        tags:
            - 'sylius_fixtures.fixture'
