services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.fixture.example_factory.general_settings:
        class: VS\ApplicationInstalatorBundle\DataFixtures\Factory\GeneralSettingsExampleFactory
        arguments:
            - '@vs_application.factory.settings'
            - '@vs_application.factory.application'
            
    vs_application.fixture.example_factory.applications:
        class: VS\ApplicationInstalatorBundle\DataFixtures\Factory\ApplicationsExampleFactory
        arguments:
            - '@vs_application.factory.application'
    
    vs_application.fixture.example_factory.taxonomy:
        class: VS\ApplicationInstalatorBundle\DataFixtures\Factory\TaxonomyExampleFactory
        arguments:
            - '@vs_application.factory.taxonomy'
            - '@vs_application.factory.taxon'
    
    vs_application.fixture.example_factory.page_categories:
        class: VS\ApplicationInstalatorBundle\DataFixtures\Factory\PageCategoriesExampleFactory
        arguments:
            - '@vs_application.repository.taxonomy'
            - '@vs_application.factory.taxon'
            - '@vs_cms.factory.page_categories'

    vs_application.fixture.example_factory.pages:
        class: VS\ApplicationInstalatorBundle\DataFixtures\Factory\PagesExampleFactory
        arguments:
            - '@vs_cms.repository.page_categories'
            - '@vs_cms.factory.pages'
            
    vs_application.fixture.example_factory.locales:
        class: VS\ApplicationInstalatorBundle\DataFixtures\Factory\LocalesExampleFactory
        arguments:
            - '@vs_application.factory.locale'
            - '@vs_application.repository.locale'
