services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    vs_app.command.install:
        class: Vankosoft\ApplicationInstalatorBundle\Command\InstallCommand
        tags:
            - 'console.command'
            
    vs_app.command.check_requirements:
        class: Vankosoft\ApplicationInstalatorBundle\Command\CheckRequirementsCommand
        tags:
            - 'console.command'
            
    vs_app.command.install.database:
        class: Vankosoft\ApplicationInstalatorBundle\Command\InstallDatabaseCommand
        tags:
            - 'console.command'
    
    vs_app.command.install.application_configuration:
        class: Vankosoft\ApplicationInstalatorBundle\Command\InstallApplicationConfigurationCommand
        tags:
            - 'console.command'
    
    vs_app.command.install.setup_super_admin:
        class: Vankosoft\ApplicationInstalatorBundle\Command\SetupSuperAdminApplicationCommand
        tags:
            - 'console.command'
    
    vs_app.command.install.setup_applications:
        class: Vankosoft\ApplicationInstalatorBundle\Command\SetupApplicationsCommand
        tags:
            - 'console.command'
    
    vs_app.command.install.application_user:
        class: Vankosoft\ApplicationInstalatorBundle\Command\CreateApplicationUserCommand
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@validator'
            - '@file_locator'
            - '@vs_cms.profile_uploader'
        tags:
            - 'console.command'
            
    vs_app.command.install.assets:
        class: Vankosoft\ApplicationInstalatorBundle\Command\InstallAssetsCommand
        tags:
            - 'console.command'
            
    vs_app.command.install.sample_data:
        class: Vankosoft\ApplicationInstalatorBundle\Command\InstallSampleDataCommand
        tags:
            - 'console.command'
            
    vs_app.command.install.extended_sample_data:
        class: Vankosoft\ApplicationInstalatorBundle\Command\InstallExtendedSampleDataCommand
        tags:
            - 'console.command'
            
    vs_app.command.install.finalize_setup:
        class: Vankosoft\ApplicationInstalatorBundle\Command\SetupFinalizeCommand
        tags:
            - 'console.command'

    