services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    vs_app.command.install:
        class: VS\ApplicationInstalatorBundle\Command\InstallCommand
        tags:
            - 'console.command'
            
    vs_app.command.check_requirements:
        class: VS\ApplicationInstalatorBundle\Command\CheckRequirementsCommand
        tags:
            - 'console.command'
            
    vs_app.command.install.database:
        class: VS\ApplicationInstalatorBundle\Command\InstallDatabaseCommand
        tags:
            - 'console.command'
            
    vs_app.command.install.sample_data:
        class: VS\ApplicationInstalatorBundle\Command\InstallSampleDataCommand
        tags:
            - 'console.command'
            
    vs_app.command.install.setup:
        class: VS\ApplicationInstalatorBundle\Command\SetupCommand
        tags:
            - 'console.command'
            
    vs_app.command.install.application_configuration:
        class: VS\ApplicationInstalatorBundle\Command\InstallApplicationConfigurationCommand
        tags:
            - 'console.command'
            
    vs_app.command.install.assets:
        class: VS\ApplicationInstalatorBundle\Command\InstallAssetsCommand
        tags:
            - 'console.command'

    