services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    vs_app.command.create_application:
        class: Vankosoft\ApplicationInstalatorBundle\Command\CreateApplicationCommand
        tags:
            - 'console.command'
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@validator'

    vs_app.command.clear_install:
        class: Vankosoft\ApplicationInstalatorBundle\Command\ClearInstallCommand
        tags:
            - 'console.command'
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@validator'
            
    vs_app.command.bumpversion:
        class: Vankosoft\ApplicationInstalatorBundle\Command\BumpVersionCommand
        tags:
            - 'console.command'

    vs_app.command.assets.sources:
        class: Vankosoft\ApplicationInstalatorBundle\Command\AssetsSourcesCommand
        arguments:
            - '@filesystem'
        tags:
            - 'console.command'

    vs_app.command.assets.dependencies:
        class: Vankosoft\ApplicationInstalatorBundle\Command\CheckAssetDependenciesCommand
        arguments:
            - '@filesystem'
        tags:
            - 'console.command'
            
    vs_app.command.installation_info:
        class: Vankosoft\ApplicationInstalatorBundle\Command\InstallationInfoCommand
        tags:
            - 'console.command'


