parameters:
    ########################################################
    # Contact Page
    ########################################################
    vs_application.contact_email: '%env(resolve:CONTACT_EMAIL)%'
    vs_application.contact.show_map: true
    vs_application.contact.show_address: true
    vs_application.contact.show_phone: true
    vs_application.contact.google_map: 'https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=18+California,+Fresno,+CA,+United+States&amp;aq=0&amp;oq=18+California+united+state&amp;sll=39.9589,-120.955336&amp;sspn=0.007114,0.016512&amp;ie=UTF8&amp;hq=&amp;hnear=18,+Fresno,+California+93727,+United+States&amp;t=m&amp;ll=36.732762,-119.695787&amp;spn=0.017197,0.100336&amp;z=14&amp;output=embed'
    vs_application.contact.google_large_map: 'https://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=18+California,+Fresno,+CA,+United+States&amp;aq=0&amp;oq=18+California+united+state&amp;sll=39.9589,-120.955336&amp;sspn=0.007114,0.016512&amp;ie=UTF8&amp;hq=&amp;hnear=18,+Fresno,+California+93727,+United+States&amp;t=m&amp;ll=36.732762,-119.695787&amp;spn=0.017197,0.100336&amp;z=14'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Vankosoft\ApplicationBundle\Controller\SettingsController:
        tags: ['controller.service_arguments']
        autowire: true
        
    Vankosoft\ApplicationBundle\Controller\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_users.security_bridge'
        
    Vankosoft\ApplicationBundle\Controller\DashboardController:
        tags: ['controller.service_arguments']
        autowire: true
    
    Vankosoft\ApplicationBundle\Controller\ApplicationExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.application'
            - '@vs_application.factory.application'
            
    Vankosoft\ApplicationBundle\Controller\SettingsExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_app.settings_manager'
            - '@vs_application.repository.application'
            - '@vs_application.repository.settings'
            - '@vs_application.factory.settings'
            - '@vs_application.repository.taxonomy'
        
    Vankosoft\ApplicationBundle\Controller\TaxonomyTaxonsController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '@vs_application.repository.taxon'
            - '@vs_application.slug_generator'
            
    Vankosoft\ApplicationBundle\Controller\PasswordGeneratorController:
        tags: ['controller.service_arguments']
        arguments:
            - '@hackzilla.password_generator.computer'
        
    Vankosoft\ApplicationBundle\Controller\ContactController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - {
              contactEmail: '%vs_application.contact_email%',
              showAddress: '%vs_application.contact.show_address%',
              showPhone: '%vs_application.contact.show_phone%',
              showMap: '%vs_application.contact.show_map%',
              googleMap: '%vs_application.contact.google_map%',
              googleLargeMap: '%vs_application.contact.google_large_map%'
            }
            - '@mailer'
            - '@vs_users.notifications'
            
    Vankosoft\ApplicationBundle\Controller\CookieConsentTranslationsExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.doctrine_dbal_cache'
            - '@vs_application.repository.cookie_consent_translation'
            
    Vankosoft\ApplicationBundle\Controller\TagsWhitelistContextsExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.tags_whitelist_context'
    
    Vankosoft\ApplicationBundle\Controller\BannersRotatorController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_cms.repository.banner_place'
            - '@liip_imagine.cache.manager'
