services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.fixture.general_settings:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\GeneralSettingsFixture
        arguments:
            # - '@sylius.manager.product'
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.general_settings'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.taxonomy:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\TaxonomyFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.taxonomy'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.page_categories:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\PageCategoriesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.page_categories'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.applications:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\ApplicationsFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.applications'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.pages:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\PagesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.pages'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.locales:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\LocalesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.locales'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.user_roles:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\UserRolesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.user_roles'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.users:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\UsersFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.users'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.cookie_consent_translations:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\CookieConsentTranslationsFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.cookie_consent_translations'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.tags_whitelist_contexts:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\TagsWhitelistContextsFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.tags_whitelist_contexts'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.tags_whitelist_tags:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\TagsWhitelistTagsFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.tags_whitelist_tags'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.widgets_groups:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\WidgetsGroupsFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.widgets_groups'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.widgets:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\WidgetsFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.widgets'
        tags:
            - 'sylius_fixtures.fixture'
