services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.fixture.example_factory.general_settings:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Factory\GeneralSettingsExampleFactory
        arguments:
            - '@vs_application.factory.settings'
            - '@vs_application.factory.application'
            
    vs_application.fixture.example_factory.applications:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Factory\ApplicationsExampleFactory
        arguments:
            - '@vs_application.factory.application'
    
    vs_application.fixture.example_factory.taxonomy:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Factory\TaxonomyExampleFactory
        arguments:
            - '@vs_application.factory.taxonomy'
            - '@vs_application.factory.taxon'
            - '@vs_application.slug_generator'
    
    vs_application.fixture.example_factory.page_categories:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Factory\PageCategoriesExampleFactory
        arguments:
            - '@vs_application.repository.taxonomy'
            - '@vs_application.factory.taxon'
            - '@vs_cms.factory.page_categories'
            - '@vs_application.slug_generator'

    vs_application.fixture.example_factory.pages:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Factory\PagesExampleFactory
        arguments:
            - '@vs_cms.repository.page_categories'
            - '@vs_cms.factory.pages'
            - '@vs_application.slug_generator'
            
    vs_application.fixture.example_factory.locales:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Factory\LocalesExampleFactory
        arguments:
            - '@vs_application.factory.locale'
            - '@vs_application.repository.locale'

    vs_application.fixture.example_factory.user_roles:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Factory\UserRolesExampleFactory
        arguments:
            - '@vs_application.repository.taxonomy'
            - '@vs_application.factory.taxon'
            - '@vs_application.repository.taxon'
            - '@vs_users.factory.user_roles'
            - '@vs_users.repository.user_roles'
            - '@vs_application.slug_generator'

    vs_application.fixture.example_factory.users:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Factory\UsersExampleFactory
        arguments:
            - '@vs_users.manager.user'
            - '@vs_users.repository.user_roles'
            - '@vs_users.factory.user_info'
            - '%locale%'
            - '@file_locator'
            
    vs_application.fixture.example_factory.cookie_consent_translations:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Factory\CookieConsentTranslationsExampleFactory
        arguments:
            - '@vs_application.factory.cookie_consent_translation'
