services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.fixture.general_settings:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\GeneralSettingsFixture
        arguments:
            # - '@sylius.manager.product'
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.general_settings'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.taxonomy:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\TaxonomyFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.taxonomy'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.page_categories:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\PageCategoriesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.page_categories'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.applications:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\ApplicationsFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.applications'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.pages:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\PagesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.pages'
        tags:
            - 'sylius_fixtures.fixture'

    vs_application.fixture.locales:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\LocalesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.locales'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.user_roles:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\UserRolesFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.user_roles'
        tags:
            - 'sylius_fixtures.fixture'
            
    vs_application.fixture.users:
        class: VS\ApplicationInstalatorBundle\DataFixtures\VankosoftApplicationFixtures\UsersFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@vs_application.fixture.example_factory.users'
        tags:
            - 'sylius_fixtures.fixture'
