services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.fixture.listener.sample_data_purger:
        class: Vankosoft\ApplicationInstalatorBundle\DataFixtures\Listener\SampleDataPurgerListener
        arguments: 
            - '@doctrine'
        tags:
            - 'sylius_fixtures.listener'