services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
 
    vs_app.subscriber.locale:
        class: Vankosoft\ApplicationBundle\EventSubscriber\LocaleSubscriber
        arguments: ['%kernel.default_locale%']
        tags: [kernel.event_subscriber]

    vs_app.subscriber.user_locale:
        class: Vankosoft\ApplicationBundle\EventSubscriber\UserLocaleSubscriber
        tags: [kernel.event_subscriber]
