services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    vs_app.requirements.settings_requirements:
        class: Vankosoft\ApplicationInstalatorBundle\Installer\Requirement\SettingsRequirements
        arguments:
            - '@translator'
    
    vs_app.requirements.extensions_requirements:
        class: Vankosoft\ApplicationInstalatorBundle\Installer\Requirement\ExtensionsRequirements
        arguments:
            - '@translator'
    
    vs_app.requirements.filesystem_requirements:
        class: Vankosoft\ApplicationInstalatorBundle\Installer\Requirement\FilesystemRequirements
        arguments:
            - '@translator'
            - '%kernel.cache_dir%'
            - '%kernel.logs_dir%'

    vs_app.requirements:
        class: Vankosoft\ApplicationInstalatorBundle\Installer\Requirement\ApplicationRequirements
        arguments:
            $requirementCollections:
                - '@vs_app.requirements.settings_requirements'
                - '@vs_app.requirements.extensions_requirements'
                - '@vs_app.requirements.filesystem_requirements'
