services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_app.installer.checker.command_directory:
        class: VS\ApplicationInstalatorBundle\Installer\Checker\CommandDirectoryChecker
        arguments:
            - '@filesystem'
            
    vs_app.installer.checker.application_requirements:
        class: VS\ApplicationInstalatorBundle\Installer\Checker\ApplicationRequirementsChecker
        arguments:
            - '@vs_app.requirements'
        
    vs_app.commands_provider.database_setup:
        class: VS\ApplicationInstalatorBundle\Installer\Provider\DatabaseSetupCommandsProvider
        arguments:
            - '@doctrine'

    vs_app.setup.locale:
        class: VS\ApplicationInstalatorBundle\Installer\Setup\LocaleSetup
        arguments:
            - '@vs_application.repository.locale'
            - '@vs_application.factory.locale'
            - '%locale%'

