services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_app.installer.checker.command_directory:
        class: Vankosoft\ApplicationInstalatorBundle\Installer\Checker\CommandDirectoryChecker
        arguments:
            - '@filesystem'
            
    vs_app.installer.checker.application_requirements:
        class: Vankosoft\ApplicationInstalatorBundle\Installer\Checker\ApplicationRequirementsChecker
        arguments:
            - '@vs_app.requirements'
        
    vs_app.commands_provider.database_setup:
        class: Vankosoft\ApplicationInstalatorBundle\Installer\Provider\DatabaseSetupCommandsProvider
        arguments:
            - '@doctrine'

    vs_app.setup.locale:
        class: Vankosoft\ApplicationInstalatorBundle\Installer\Setup\LocaleSetup
        arguments:
            - '@stof_doctrine_extensions.listener.translatable'
            - '@vs_application.repository.locale'
            - '@vs_application.factory.locale'
            - 'en_US'
    
    vs_application.installer.setup_application:
        class: Vankosoft\ApplicationInstalatorBundle\Installer\Setup\ApplicationSetup
        arguments: 
            - '@service_container'
            - '@twig'
            - '@vs_application.slug_generator'

