parameters:
    vs_application.in_maintenance: false
services:
    vs_app.twig.alerts:
        class: Vankosoft\ApplicationBundle\Twig\Alerts
    
    vs_app.listener.maintenance:
        class: Vankosoft\ApplicationBundle\EventListener\MaintenanceListener
        arguments: 
            - '@service_container'
            - '@twig'
            - "@request_stack"
            - '@security.token_storage'
            - '@vs_application.context.application'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
