services:
    _defaults:
        autowire: true
        autoconfigure: true
       
    vs_application.maker.doctrine.entity_class_generator:
        class: Vankosoft\ApplicationBundle\Maker\Doctrine\EntityClassGenerator
        arguments:
            - '@kernel'
            - '@maker.generator'
            - '@maker.doctrine_helper'
            
    vs_application.maker.renderer.form_type_renderer:
        class: Vankosoft\ApplicationBundle\Maker\Renderer\FormTypeRenderer
        arguments:
            - '@kernel'
            - '@maker.generator'
            
    vs_application.maker.make_resource:
        class: Vankosoft\ApplicationBundle\Maker\MakeResourceCrud
        arguments:
            - '@kernel'
            - '@maker.doctrine_helper'
            - '@vs_application.maker.renderer.form_type_renderer'
            - '@vs_application.repository.application'
            - '@vs_application.repository.settings'
            - '@vs_application.slug_generator'
        tags: ['maker.command']
        
    vs_application.maker.make_taxonomy_resource:
        class: Vankosoft\ApplicationBundle\Maker\MakeTaxonomyResourceCrud
        arguments:
            - '@kernel'
            - '@maker.doctrine_helper'
            - '@vs_application.maker.renderer.form_type_renderer'
            - '@vs_application.repository.application'
            - '@vs_application.repository.settings'
            - '@vs_application.slug_generator'
        tags: ['maker.command']
        
    vs_application.maker.make_resource_entity:
        class: Vankosoft\ApplicationBundle\Maker\MakeResourceEntity
        arguments:
            - '@maker.file_manager'
            - '@maker.doctrine_helper'
            - '@maker.generator'
            - '@vs_application.maker.doctrine.entity_class_generator'
            - '@maker.php_compat_util'
        tags: ['maker.command']

    vs_application.maker.make_theme:
        class: Vankosoft\ApplicationBundle\Maker\MakeTheme
        arguments:
            - '@kernel'
            - '@vs_application.slug_generator'
        tags: ['maker.command']

