parameters:
    vankosoft_host: '%env(HOST)%'
    vs_application.menu.config_file: "%kernel.project_dir%/config/admin-panel/packages/vs_application.yaml"
    vs_application.main_menus: ['profileMenu', 'mainSystemMenu', 'mainCmsMenu']

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    vs_application.path_roles_service:
        class: Vankosoft\ApplicationBundle\Component\Menu\PathRolesService
        arguments: ['@security.access_map']

    vs_app.menu_builder:
        class: Vankosoft\ApplicationBundle\Component\Menu\MenuBuilder
        arguments:
            - "%vs_application.menu.config_file%"
            - "@security.authorization_checker"
            - "@vs_application.path_roles_service"
            - "@router"
            - "@parameter_bag"
            - "@translator"
            - '@request_stack'
            
    vs_app.profile_menu:
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", profileMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: profile }
    
    vs_app.main_menu_system:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", mainMenu]
        arguments: ["@knp_menu.factory", 'mainSystemMenu']
        tags:
            - { name: knp_menu.menu, alias: mainSystem }
            
    vs_app.main_menu_cms:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", mainMenu]
        arguments: ["@knp_menu.factory", 'mainCmsMenu']
        tags:
            - { name: knp_menu.menu, alias: mainCms }

    vs_app.breadcrumbs_menu:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", breadcrumbsMenu]
        arguments: ["@knp_menu.factory", "%vs_application.main_menus%"]
        tags:
            - { name: knp_menu.menu, alias: breadcrumbs }
