services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_app.settings_manager:
        class: Vankosoft\ApplicationBundle\Component\Settings\Settings
        arguments: 
            - '@service_container'
            - '@vs_application.doctrine_dbal_cache'

