services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Make Themes Repository public to can get it from Container
    vs_app.theme_repository:
        alias: sylius.repository.theme
        public: true
        
    vs_app.listener.theme_change:
        class: Vankosoft\ApplicationBundle\EventListener\ThemeChangeListener
        arguments:
            - '@sylius.theme.context.settable'
            - '@sylius.repository.theme'
            - '@vs_application.repository.settings'
            - '@vs_application.context.application'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
