services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.data_collector.core:
        class: Vankosoft\ApplicationBundle\DataCollector\VsApplicationCollector
        arguments:
            - '@vs_application.project_type'
            - '@vs_application.repository.locale'
            - '@vs_application_instalator.repository.instalation_info'
            - '%vs_application.version%'
            - '%kernel.bundles%'
            - '%locale%'
        tags:
            -
                name: data_collector
                # must match the value returned by the getName() method
                id: 'vs_application.core_collector'
                # optional template (it has more priority than the value returned by getTemplate())
                template: '@VSApplication/DataCollector/vs_application.html.twig'
                # optional priority (positive or negative integer; default = 0)
                # priority: 300
    
    vs_application.data_collector.application:
        class: Vankosoft\ApplicationBundle\DataCollector\ApplicationCollector
        arguments:
            - '@vs_application.repository.application'
            - '@vs_application.context.application'
        tags:
            -
                name: data_collector
                id: 'vs_application.application_collector'
                template: '@VSApplication/DataCollector/application.html.twig'
    
    
    
