parameters:
    vankosoft_host: '%env(HOST)%'
    vs_application.menu.config_file: "%kernel.project_dir%/config/packages/vs_application.yaml"
    vs_application.main_menus: ['mainMenu']

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    vs_application.path_roles_service:
        class: VS\ApplicationBundle\Component\Menu\PathRolesService
        arguments: ['@security.access_map']

    vs_app.menu_builder:
        class: VS\ApplicationBundle\Component\Menu\MenuBuilder
        arguments:
            - "%vs_application.menu.config_file%"
            - "@security.authorization_checker"
            - "@vs_application.path_roles_service"
            - "@router"
            - "@parameter_bag"
        calls:
          - [ setContainer ]
            
    vs_app.profile_menu:
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", profileMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: profile }
    
    vs_app.main_menu:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", mainMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: main }

    vs_app.breadcrumbs_menu:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", breadcrumbsMenu]
        arguments: ["@knp_menu.factory", "%vs_application.main_menus%"]
        tags:
            - { name: knp_menu.menu, alias: breadcrumbs }
