parameters:
    vs_application.taxon_repository_throw_exception: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    vs_application.repository.taxon:
        class: Vankosoft\ApplicationBundle\Repository\TaxonRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - '%vs_application.model.taxon.class%'
        calls:
            - [ setRootDir, [ '%kernel.project_dir%' ] ]
            - [ throwException, [ '%vs_application.taxon_repository_throw_exception%' ] ]
            
#     Vankosoft\ApplicationBundle\Repository\TaxonDescendentRepository:
#     
#         calls:
#             - [ setContainer, [ '@service_container' ] ]
        

