<?php namespace Vankosoft\UsersBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * Users Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository implements UsersRepositoryInterface
{
    public function countTotal() 
    {
        $query = $this->getEntityManager()->createQuery('SELECT COUNT(u) FROM VSUsersBundle:User u');

        return $query->getSingleScalarResult();
    }
}

