<?php namespace VS\UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Users Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function countTotal() 
    {
        $query = $this->getEntityManager()->createQuery('SELECT COUNT(u) FROM IAUsersBundle:User u');

        return $query->getSingleScalarResult();
    }
}

