vs_application_dashboard:
    path: /dashboard
    controller: Vankosoft\ApplicationBundle\Controller\DashboardController::index
    
vs_application_login:
    path: /login
    controller: Vankosoft\ApplicationBundle\Controller\AuthController::login

# vs_application_login_check:
#     path: /login_check
    
vs_application_logout:
    path: /logout
    controller: Vankosoft\ApplicationBundle\Controller\AuthController::logout
    
vs_application_contact:
    path: /contact
    controller: Vankosoft\ApplicationBundle\Controller\ContactController::index


