vs_application_settings:
    resource: |
        alias: vs_application.settings
        path: /settings/preferences
        templates: "@VSApplication/Pages/Settings"
    type: sylius.resource

vs_application_application_form:
    path: /settings/application-edit/form-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\ApplicationExtController::index
    
vs_application_application_handle:
    path: /settings/application-edit/handle-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\ApplicationExtController::handle
    
vs_application_application_remove:
    path: /settings/application-edit/remove-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\ApplicationExtController::remove

vs_application_settings_form:
    path: /settings/settings-edit/form-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\SettingsExtController::index

vs_application_settings_handle:
    path: /settings/settings-edit/handle-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\SettingsExtController::handle


vs_application_locales:
    resource: |
        alias: vs_application.locale
        except: ['show']
        path: /settings/locales
        templates: "@VSApplication/Pages/Locales"
    type: sylius.resource
    
vs_application_cookie_consent_translations:
    resource: |
        alias: vs_application.cookie_consent_translation
        except: ['show']
        path: /settings/cookie-consent-translations
        templates: "@VSApplication/Pages/CookieConsentTranslations"
    type: sylius.resource
    
vs_application_whitelist_context_update_tags:
    path: /whitelist-context/{contextId}/update-tags
    controller: Vankosoft\ApplicationBundle\Controller\TagsWhitelistContextsExtController::updateTagsWhitelistContextTagsAction
