vs_application_taxonomy:
    resource: |
        alias: vs_application.taxonomy
        path: /taxonomy
        templates: "@VSApplication/Pages/Taxonomy"
    type: sylius.resource
    options:
        expose: true

vs_application_taxon:
    path: /taxonomy/taxons
    controller: Vankosoft\ApplicationBundle\Controller\TaxonController::index

vs_application_taxonomy_taxons:
    path: /taxonomy_{id}/taxons
    controller: Vankosoft\ApplicationBundle\Controller\TaxonomyTaxonsController::index
    
vs_application_taxonomy_taxons_gtreetable:
    path: /taxonomy_{taxonomyId}/taxons/gtreetable
    controller: Vankosoft\ApplicationBundle\Controller\TaxonomyTaxonsController::gtreeTableSource

vs_application_taxonomy_taxons_easyui_combotree:
    path: /taxonomy_{taxonomyId}/taxons/easyui-combotree
    controller: Vankosoft\ApplicationBundle\Controller\TaxonomyTaxonsController::easyuiComboTreeSource
    
vs_application_taxonomy_taxon_edit:
    path: /taxonomy-taxon/{taxonomyId}
    controller: Vankosoft\ApplicationBundle\Controller\TaxonomyTaxonsController::editTaxon
    
vs_application_taxonomy_taxon_handle:
    path: /taxonomy-taxon/{taxonomyId}/handle
    controller: Vankosoft\ApplicationBundle\Controller\TaxonomyTaxonsController::handleTaxon

vs_application_tags_whitelist_context:
    resource: |
        alias: vs_application.tags_whitelist_context
        except: ['show']
        path: /settings/tags-whitelist-contexts
        templates: "@VSApplication/Pages/TagsWhitelistContext"
    type: sylius.resource
