vs_application_widget_group:
    resource: |
        alias: vs_application.widget_group
        path: /widgets-groups
        templates: "@VSApplication/Pages/WidgetGroup"
    type: sylius.resource
    options:
        expose: true
        
vs_application_widget:
    resource: |
        alias: vs_application.widget
        path: /widgets
        templates: "@VSApplication/Pages/Widget"
    type: sylius.resource
    options:
        expose: true

vs_application_widget_ext_json_roles:
    path: /widget-ext/json-roles/{editWidgetId}
    controller: Vankosoft\ApplicationBundle\Controller\WidgetsExtController::rolesEasyuiComboTreeWithSelectedSource

vs_application_widget_ext_index:
    path: /widget-ext/listing
    controller: Vankosoft\ApplicationBundle\Controller\WidgetsConfigsController::index
    
vs_application_widget_ext_refresh:
    path: /widget-ext/refresh-{all}
    controller: Vankosoft\ApplicationBundle\Controller\WidgetsConfigsController::refresh
    defaults: { all: 0 }
    
vs_application_widget_ext_refresh_all_users:
    path: /widget-ext/refresh-all-users-{all}
    controller: Vankosoft\ApplicationBundle\Controller\WidgetsConfigsController::refreshAllUsers
    defaults: { all: 0 }
    
vs_application_widget_ext_load:
    path: /widget-ext/load/{widgetId}
    controller: Vankosoft\ApplicationBundle\Controller\WidgetsConfigsController::load

vs_application_widget_ext_status:
    path: /widget-ext/status/{widgetId}/{status}
    controller: Vankosoft\ApplicationBundle\Controller\WidgetsConfigsController::status
    requirements:
        status: \d+

vs_application_widget_ext_config:
    path: /widget-ext/config/{widgetId}
    controller: Vankosoft\ApplicationBundle\Controller\WidgetsConfigsController::configs

vs_application_widget_ext_order:
    path: /widget-ext/order/{widgetId}/{order}
    controller: Vankosoft\ApplicationBundle\Controller\WidgetsConfigsController::order
    requirements:
        order: \d+
